image: gradle:latest

api:
  trigger:
    include: api/.gitlab-ci.yml
    strategy: depend
  rules:
    - changes: [api/*]

domain:
  trigger:
    include: domain/.gitlab-ci.yml
    strategy: depend
  rules:
    - changes: [domain/*]