image: gradle:latest

stages:
  - build

build:
  stage: build
  script: gradle clean build
  artifacts:
    when: always
    reports:
      junit: "*/build/test-results/test/TEST-*.xml"
      coverage_report:
        coverage_format: cobertura
        path: "*/build/reports/jacoco/test/html/index/html"

