image: gradle:latest

stages:
  - build

build:
  stage: build
  script: gradle clean build --continue
  coverage: /Method Coverage..?(\d|\.){1,4}%/
  artifacts:
    when: always
    reports:
      junit:
        - "*/build/test-results/test/TEST-*.xml"
