image: gradle:latest

stages:
  - build

build:
  stage: build
  script: gradle clean build
  artifacts:
    when: always
    reports:
      junit: "*/build/test-results/test/TEST-*.xml"
      jacoco:  "*/build/reports/jacoco/test/html/index.html"

