image: gradle:latest

stages:
  - build

build:
  stage: build
  script: gradle clean build
  artifacts:
    when: always
    reports:
      junit:
        - domain/build/test-results/test/TEST-*.xml
        - api/build/test-results/test/TEST-*.xml

