image: gradle:latest

stages:
  - build

build:
  stage: build
  script: gradle clean build --continue
  coverage: /Line Coverage.\s(\d{1,3}\.\d)%/
  artifacts:
    when: always
    reports:
      junit:
        - "*/build/test-results/test/TEST-*.xml"
